<div class="wrap">
    <h2><?php _e('Reassign Content', 'cma-answers'); ?></h2>
    <?php echo CMA_BaseController::getAdminNav(); ?>
    <div class="clear"></div>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">The Reassign Content feature allows administrators to transfer all forum content, including questions, answers, and comments, from one user to another. This tool simplifies content management and ensures that discussions remain organized when users are reassigned or leave the platform.</p>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:600px; float:left; margin-right:20px;">
            <a href="<?php echo CMA_URL . '/views/resources/imgs/cm-answers-reassign-content.png'; ?>" target="_blank" style="text-decoration:none;">
                <img src="<?php echo CMA_URL . '/views/resources/imgs/cm-answers-reassign-content.png'; ?>" alt="" style="width:100%; border:1px solid #444;" />
            </a>
            <span style="font-size:15px;">Reassinging content</span>
        </div>
    </div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Reassigning all content (questions, answers, comments) from one user to another.</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Managing content transfers for more efficient user account management.</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Keeping forum content intact while ensuring correct user attribution.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cma_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>