<div class="wrap">
    <h2><?php _e('Categories', 'cma-answers'); ?></h2>
    <?php echo CMA_BaseController::getAdminNav(); ?>
    <div class="clear"></div>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">Enhance content organization and user navigation with the Pro version of CM Answers. The Categories feature provides powerful tools to structure and manage discussions effectively.</p>
<div style="float:left; width:100%; margin-bottom:30px;">
    <div style="text-align:center; width:300px; float:left; margin-right:20px;">
        <a href="<?php echo CMA_URL . '/views/resources/imgs/cm-answers-categories.png'; ?>" target="_blank" style="text-decoration:none;">
            <img src="<?php echo CMA_URL . '/views/resources/imgs/cm-answers-categories.png'; ?>" alt="" style="width:100%; border:1px solid #444;" />
        </a>
        <span style="font-size:15px;">Managing categories</span>
    </div>
</div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Creating unlimited categories to organize questions and answers.</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Assigning questions to multiple categories for better flexibility.</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Offering users intuitive filtering options by category.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cma_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>