<?php

require_once CMA_PATH . '/lib/helpers/SettingsView.php';
$settingsView = new CMA_SettingsView();

$tabs = apply_filters('cma_settings_pages', CMA_Settings::$categories);
?>

<p class="clear">
<?php do_action('cma_flash_messages');
if (!empty($messages)):
    foreach ($messages as $message):
        ?>
        <div class="updated"><p><?php echo $message; ?></p></div><?php
    endforeach;
endif; ?>

<?php require('settings/top.phtml'); ?>

<?php

// check permalink settings

if (get_option('permalink_structure') == '') {

    echo '<span style="color:red">Your WordPress Permalinks needs to be set to allow plugin to work correctly. Please Go to <a href="'

        . esc_attr(admin_url()) . 'options-permalink.php" target="new">Settings->Permalinks</a> to set Permalinks to Post Name.</span><br><br>';

}

?>

<form method="post" enctype="multipart/form-data" id="cm-answers-settings-form">

    <input id="cma_settings_search" placeholder="Search in settings..."><span id="cma_settings_search_clear">&times;</span>

    <div id="tabs">
        <ul id="cma-tab-menu"><?php foreach ($tabs as $id => $name ): ?>
                <li><a href="#tab_<?php echo $id; ?>"><?php echo CMA_Settings::__($name); ?></a></li>
            <?php endforeach; ?></ul>


        <?php foreach ($tabs as $id => $name): ?>
            <div id="tab_<?php echo $id; ?>" class="cma-tab-content"><?php

                $path = dirname(__FILE__) . '/settings/'. $id .'.phtml';
                ob_start();
                if (file_exists($path)) require($path);
                else echo $settingsView->renderCategory($id);
                $output = ob_get_clean();
                echo apply_filters('cma_settings_page_content', $output, $id, $name, $path);

                ?></div>
        <?php endforeach; ?>
    </div>
    <input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce(CMA_BaseController::ADMIN_SETTINGS)); ?>" />
    <input type="submit" class="button button-primary" value="<?php echo esc_attr(CMA_Settings::__('Update')); ?>" />
</form>


